apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
  namespace: {{{ M3_NAMESPACE }}}
  labels:
    app: posts-deployment
spec:
  replicas: {{{ M3_REPLICAS }}}
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: main-service
          image: "{{{M3_IMAGE}}}:{{{M3_VERSION}}}"
          command: ['node']
          args: ['index.js']
          env:
            - name: PORT
              value: '3000'
            - name: APP_NAME
              value: posts
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
        - name: mock-service
          image: "{{{M3_MOCK_IMAGE}}}"
          args:
            [
              'mock',
              '-d',
              '-h',
              '0.0.0.0',
              'https://raw.githubusercontent.com/m3ntorship/backend-nestjs-template/ci-cd/openapi/example.openapi.yml',
            ]
          ports:
            - name: web
              containerPort: 4010
              protocol: TCP
