apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pickify
  namespace: {{{M3_NAMESPACE}}}
spec:
  rules:
    - host: '{{{M3_DNS_VALUE}}}.{{{M3_HOST_NAME}}}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pickify-posts
                port:
                  number: {{{M3_PORT_BACKEND}}}
    - host: '{{{M3_DNS_VALUE}}}-mock.{{{M3_HOST_NAME}}}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pickify-posts
                port:
                  number: {{{M3_PORT_BACKEND_MOCK}}}
